### ISSUE TITLE
come far funzionare l'app?

### ISSUE THREAD

**Issue by BerniApple** [SergioArc69/invio_schedine-alloggiatiweb#1]
Ciao, perdona l'ignoranza ma come posso far funzionare l'app? potresti fare una guida step by step?
grazie

**Comment by SergioArc69** [comment]
Oltre a ricompilare i sorgenti,
è possibile scaricare il setup dalla seguente URL:
https://github.com/SergioArc69/invio_schedine-alloggiatiweb/releases/download/v1.0.1/InvioSchedineAlloggiatiWeb_setup.zip

Una volta installata l'applicazione, occorre usare le credenziali e la WsKey del sito AlloggiatiWeb
in modo da poter eseguire il login per generare il token (che può essere verificato clickando su "CkToken")

A questo punto è possibile caricare un file "schedine" (ad esempio di quelli prodotti da 
https://tourtaxmain.servizienti.it/TourTaxFO ), che alla bisogna può essere modificato e quindi eseguirne la verifica e l'invio.

Come da specifiche, dal giorno successivo, è possibile eseguire il download della ricevuta, in pdf, degli invii effettuati.
