### ISSUE TITLE
Credenziali di test per accesso

### ISSUE THREAD

**Issue by bgvsan** [SergioArc69/invio_schedine-alloggiatiweb#2]
Ciao, volevo sapere come erano state testate le chiamate al servizio?
si puo avere accesso a una utenza di test?

**Comment by SergioArc69** [comment]
Ciao
Io ho implementato l'applicazione basandomi sulla documentazione pubblicata da AlloggiatiWeb.
Il funzionamento l'ho verificato usando le credenziali reali, collegate al mio B&B, in occasione della registrazione di diversi ospiti.

Non ho idea se è possibile richiedere delle credenziali di test, mi dispiace.
